version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: arvore_pao_n8n
    restart: always
    environment:
      - N8N_PROTOCOL=http
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_LOG_LEVEL=info
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - arvore_pao_net # Conecta o serviço à rede definida abaixo

volumes:
  n8n_data:

networks:
  arvore_pao_net:
    # Informa ao Compose para usar uma rede que já existe
    name: arvore_pao_system_arvore_pao_network # Nome real da rede criada pelo docker-compose.yml
    external: true