version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: arvore_pao_n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=arvore_pao_2025
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      - N8N_LOG_LEVEL=info
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - arvore_pao_network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5678/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  arvore_pao_network:
    external: true
    name: arvore_pao_system_arvore_pao_network
